version: '3'
services:     
  gtun:
    image: ickelin/gtun:latest
    container_name: gtun
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /opt/apps/logs:/opt/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
       forwards:
          CN: 
            server: "127.0.0.1:9098"
            authKey: "rewrite with your auth key"
            tcp:
              listen: ":8524"
            udp:
              listen: ":8525"

        log:
          days: 5
          level: "info"
          path: "/opt/logs/gtun.log"