version: '3'
services:     
  gtun:
    build: .
    container_name: gtun
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /opt/apps/logs:/opt/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
        forwards:
          - region: US
            tcp:
              listen: ":2012"
            udp:
              listen: ":2012"
            transport:
              - server: "ip:port"
                scheme: kcp
                traceAddr: ""
            rateLimit: 1000

        log:
          days: 5
          level: "info"
          path: "gtun.log"