version: '3'
services:     
  gtun:
    build: .
    container_name: gtun
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /opt/apps/logs:/opt/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
        settings:
          CN:
            route:
              - trace_addr: ""
                scheme: "kcp"
                addr: ""
                auth_key: ""
            proxy:
              "tproxy_tcp": |
                {
                  "read_timeout": 30,
                  "write_timeout": 30,
                  "listen_addr": ":8524",
                  "rate_limit": 50,
                  "region": "CN"
                }
              "tproxy_udp": |
                {
                  "read_timeout": 30,
                  "write_timeout": 30,
                  "session_timeout": 30,
                  "listen_addr": ":8524",
                  "rate_limit": 50,
                  "region": "CN"
                }
              "tun_proxy": |
                {
                  "mtu": 1400,
                  "region": "CN",
                  "read_timeout": 10,
                  "write_timeout": 10
                }
        log:
          days: 5
          level: Debug
          path: gtun.log