version: '3'
services:     
  gtund:
    build: .
    container_name: gtund
    restart: always
    network_mode: host
    volumes:
      - /opt/apps/logs:/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
        server:
          - listen: ":3002"
            authKey: "rewrite with your auth key"
            scheme: "kcp"
            trace: ":3003"

        log:
          days: 5
          level: "debug"
          path: "gtund.log"
