version: '3'
services:     
  gtund:
    build: .
    container_name: gtund
    restart: always
    network_mode: host
    volumes:
      - /opt/apps/logs:/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
        server:
          - listen: ":3002"
            authKey: "rewrite with your auth key"
            scheme: "kcp"

          - listen: ":3001"
            authKey: "rewrite with your auth key"
            scheme: "mux"

        log:
          days: 5
          level: "info"
          path: "/logs/gtund.log"