version: '3'
services:     
  gtund:
    image: ickelin/gtund:latest
    container_name: gtund
    restart: always
    ports:
      - 9098:9098/udp
    volumes:
      - /opt/apps/logs:/opt/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
        server:
          listen: ":9098"
          authKey: "rewrite with your auth key"
          scheme: "kcp"

        log:
          days: 5
          level: "info"
          path: "/opt/logs/gtund.log"