version: '3'
services:     
  gtund:
    build: .
    container_name: gtund
    restart: always
    ports:
      - 9098:9098/udp
    volumes:
      - /opt/apps/logs:/opt/logs
    environment:
      TIME_ZONE: Asia/Shanghai
      settings: |
        server:
          - listen: ":3002"
            authKey: "rewrite with your auth key"
            scheme: "kcp"

          - listen: ":3001"
            authKey: "rewrite with your auth key"
            scheme: "mux"

        log:
          days: 5
          level: "info"
          path: "gtund.log"